# Generated by Django 4.2.12 on 2026-02-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='affiches/')),
                ('date_sortie', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_rangees', models.PositiveIntegerField()),
                ('nombre_places_par_rangee', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.salle')),
            ],
            options={
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=10)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangee', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.salle')),
            ],
            options={
                'unique_together': {('salle', 'rangee', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.place')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='cinema.reservation')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seance')),
            ],
            options={
                'unique_together': {('place', 'seance')},
            },
        ),
    ]
